spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskcore_db}
    username: ${DB_USERNAME:taskcore_admin}
    password: ${DB_PASSWORD:admin_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    github.oliveira.gb.taskcore: DEBUG