name: TaskCore CI/CD

on:
  push:
    branches: [ "main", "develop", "feature/*", "test/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Dar permissão de execução ao mvnw
        run: chmod +x mvnw

      - name: Executar testes
        run: ./mvnw clean test

      - name: Salvar relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-testes-maven
          path: target/surefire-reports/